import { Geist, Geist_Mono, Montserrat, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import NavBar from "@/components/shared/NavBar";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets : ["latin"],
  weight:["400","500","600","700","800"]
})

export const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ["latin"],
  weight:['200','300','400','500','600','700','800','900']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.className} h-full antialiased`}
    >
      <body className={`min-h-full flex flex-col`} data-theme="light">
       
        <main>
          {children}
        </main>
        </body>
    </html>
  );
}
